spring:
  application:
    name: ecommerce-backend
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user     # Tài khoản bạn đã tạo trong Docker
    password: 3821     # Mật khẩu bạn đã tạo trong Docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Tạm thời dùng update để Spring Boot tự tạo bảng
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
  # Cấu hình thủ công ở đây dư thừa vì từ springboot3 trở lên tich hợp sẵn JavaTimeModule
    # serialization: 
    #   write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /api/v1  # Base URL cho tất cả API

jwt:
  secret: WH1q@d,Qfc2NWF#ki#X}$pc4(z2Kte+*]![n/q6}fYWRVcJ{Ku?uqX#_lB_!&/f/^J7-0/u3:1QwUP(wUH;@&q
  expiration: 86400000       # 24 giờ (ms)
  refresh-expiration: 604800000  # 7 ngày (ms)

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method